[package]
name = "prng_well1024a"
version = "0.1.0"
authors = ["Helge Skogly Holm <helge.holm@gmail.com>"]

[dependencies]
rand = "0.3.0"

[[bin]]
name = "test"
path = "src/main.rs"
doc = false

[lib]
name = "prng_well1024a"
path = "src/lib.rs"
